### ISSUE TITLE
Create a model of the wishlist

### ISSUE THREAD

**Issue by yiyangwg** [Devops-Wishlists/wishlists#16]
**As a** developer
**I need** a wishlist model and a item model
**So that** our model can hold definitions of our resource

**Assumptions:**
* wishlist model
1. id
2. collection of items
* item model
1. id
2. name
3. description
4. priority level

**Acceptance Criteria:**
```
Given the inputs above, the model should be instantiated without any errors
```

**Comment by AbduGadir** [comment]
As we are using database, I'm suggesting following model (sure we will write in separate classes):

users = Table('users', metadata,
    Column('wishlist-id', Integer, primary_key=True),
    Column('wishlist-name', String(40)),
    Column('user-id', Integer),
)

from sqlalchemy import PrimaryKeyConstraint

items = Table('items', metadata,
            Column('item-id', Integer),
            Column('wishlist-id', Integer, ForeignKey('users.wishlist-id')),
            Column('description', String(100)),
            PrimaryKeyConstraint('item-id', 'wishlist-id', name='items_pk')
        )
