### ISSUE TITLE
Create a Vagrantfile for local dev

### ISSUE THREAD

**Issue by yiyangwg** [Devops-Wishlists/wishlists#2]
**As a** developer 
**I need** a Vagrantfile to get Vagrant set up 
**So that** all the other developers of our team can use this development environment

**Assumptions:**
* All developers have Vagrant installed
* We need a Vagrantfile

**Acceptance Criteria:**
```
Run vagrant up and vagrant ssh without error on everyone's machines
```

**Comment by dzliang100** [comment]
For the acceptance criteria, I think it'd be good to say what should happen after 'run vagrant up and vagrant ssh' (e.g. runs without error, project runs with correct dependencies loaded, etc.)
