### ISSUE TITLE
Create a runtime.txt file 

### ISSUE THREAD

**Issue by akethnyu** [Devops-Wishlists/wishlists#43]
**As a** Developer
**I need**  runtime.txt file 
**So that** the environment is automatically setup when deploying to the cloud

**Assumptions:**
* 

**Acceptance Criteria:**
```
When 
Then
```

**Comment by yiyangwg** [comment]
I think we need a runtime.txt instead of a requirements.txt since professor mentions the runtime.txt in his assignment.
