### ISSUE TITLE
Add item description

### ISSUE THREAD

**Issue by dzliang100** [Devops-Wishlists/wishlists#5]
**As a** User
**I need** to add a description to an item on a wishlist
**So that** I can know my thoughts about the item for later

**Assumptions:**
* There is no description currently with the item.
* API Call: PUT /wishlists/{id}/{item-id}/description

**Acceptance Criteria:**
```
When I type a description and click "add a description",
I should see the description below the item.
```

**Comment by AbduGadir** [comment]
The same as update an item. Should we still need it?

**Comment by dzliang100** [comment]
I think it's very similar but still a bit different. I noticed that the description of an item can be null, so adding an item description would be when there is no description initially for the item, and updating an item would be for updating the item description.
