### ISSUE TITLE
Read item description

### ISSUE THREAD

**Issue by dzliang100** [Devops-Wishlists/wishlists#6]
**As a** User
**I need** to read an item's description
**So that** I know more about the item

**Assumptions:**
* By default, a user should see the item name with the description
when viewing all items in a list
* API Call: GET /items/{item-id}/description

**Acceptance Criteria:**
```
When I view all the items in a list,
I should see the descriptions that I wrote
for items underneath each item in the list.
If I didn't write a description yet,
I should see a blank space underneath the item.
```

**Comment by AbduGadir** [comment]
On other calls, a list of objects is returned, this method returns a partial object, do you guys have any preference about the return type? What is the difference between this one and the get item call? Are we still keeping this?
